version: '3.9'
services:
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 8080:8080